kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-role
subjects:
- kind: ServiceAccount
  name: admin-role
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: awayt
  namespace: default
rules:
- apiGroups: [ "" ]
  resources: [ "pods"]
  verbs: [ "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: awayt
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: awayt
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
